spring:
  application:
    name: whisperQ
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/whisperq
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.show_sql]": true
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect

  jackson:
    time-zone: Asia/Seoul
